-- MySQL Script generated by MySQL Workbench
-- Mon May 23 23:07:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Executive`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `Executive`;
CREATE TABLE IF NOT EXISTS `Executive` (
    `ID` VARCHAR(45) NOT NULL,
    `First_Name` VARCHAR(45) NOT NULL,
    `Last_Name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `Program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Program`;
CREATE TABLE IF NOT EXISTS `Program` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(45) NOT NULL,
    `ELIDEK_Sector` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `Foundation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Foundation`;
CREATE TABLE IF NOT EXISTS `Foundation` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(45) NOT NULL,
    `Abbreviation` VARCHAR(45) NOT NULL,
    `Postal_Code` INT NOT NULL,
    `Street` VARCHAR(45) NOT NULL,
    `Street_Number` VARCHAR(10) NOT NULL,
    `City` VARCHAR(45) NOT NULL,
    `Foundation_Phone_1` VARCHAR(45) NOT NULL,
    `Foundation_Phone_2` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
)  ENGINE=INNODB ROW_FORMAT=DEFAULT;


-- -----------------------------------------------------
-- Table `Foundation_Phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Foundation_Extra_Phones`;
CREATE TABLE IF NOT EXISTS `Foundation_Extra_Phones` (
    `Phone_Number` VARCHAR(45) NOT NULL,
    `Foundation_ID` INT NOT NULL,
    PRIMARY KEY (`Phone_Number`),
    INDEX `fk_Foundation_Extra_Phones_Foundation1_idx` (`Foundation_ID` ASC),
    CONSTRAINT `fk_Foundation_Extra_Phones_Foundation1` FOREIGN KEY (`Foundation_ID`)
        REFERENCES `Foundation` (`ID`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `Researcher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Researcher`;
CREATE TABLE IF NOT EXISTS `Researcher` (
  `ID` VARCHAR(45) NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Sex` VARCHAR(15) NOT NULL,
  `Birth_Date` DATE NOT NULL,
  `Foundation_ID` INT NOT NULL,
  `Foundation_Date` DATE NOT NULL,
  `Age` int AS (round(datediff(curdate(), birth_date)/365, 0)),
  PRIMARY KEY (`ID`),
  INDEX `fk_Researcher_Foundation1_idx` (`Foundation_ID` ASC),
  CONSTRAINT `fk_Researcher_Foundation1`
    FOREIGN KEY (`Foundation_ID`)
    REFERENCES `Foundation` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Researcher_works_on_Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Researcher_works_on_Project`;
CREATE TABLE IF NOT EXISTS `Researcher_works_on_Project` (
    `Researcher_ID` VARCHAR(45) NOT NULL,
    `Project_ID` INT NOT NULL,
    PRIMARY KEY (`Researcher_ID` , `Project_ID`),
    INDEX `fk_Researcher_has_Project_Project1_idx` (`Project_ID` ASC),
    INDEX `fk_Researcher_has_Project_Researcher1_idx` (`Researcher_ID` ASC),
    CONSTRAINT `fk_Researcher_works_on_Project_Researcher1` FOREIGN KEY (`Researcher_ID`)
        REFERENCES `Researcher` (`ID`)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_Researcher_works_on_Project_Project1` FOREIGN KEY (`Project_ID`)
        REFERENCES `Project` (`ID`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `Scientific_Field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scientific_Field`;
CREATE TABLE IF NOT EXISTS `Scientific_Field` (
    `Name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`Name`)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `Project_Scientific_Field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project_Scientific_Field`;
CREATE TABLE IF NOT EXISTS `mydb`.`Project_Scientific_Field` (
    `Project_ID` INT NOT NULL,
    `Scientific_Field_Name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`Project_ID` , `Scientific_Field_Name`),
    INDEX `fk_Project_has_Scientific_Field_Project1_idx` (`Project_ID` ASC),
    INDEX `fk_Project_Scientific_Field_Scientific_Field1_idx` (`Scientific_Field_Name` ASC),
    CONSTRAINT `fk_Project_has_Scientific_Field_Project1` FOREIGN KEY (`Project_ID`)
        REFERENCES `mydb`.`Project` (`ID`)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_Project_Scientific_Field_Scientific_Field1` FOREIGN KEY (`Scientific_Field_Name`)
        REFERENCES `mydb`.`Scientific_Field` (`Name`)
        ON DELETE NO ACTION ON UPDATE CASCADE
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project`;
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `Title` VARCHAR(79) NOT NULL,
    `Start_Date` DATE NOT NULL,
    `End_Date` DATE NOT NULL,
    `Summary` TEXT NULL,
    `Funding` FLOAT NOT NULL,
    `Executive_ID` VARCHAR(45) NOT NULL,
    `Program_ID` INT NOT NULL,
    `Foundation_ID` INT NOT NULL,
    `Researcher_ID_Boss` VARCHAR(45) NOT NULL,
    `Researcher_ID_eval` VARCHAR(45) NOT NULL,
    `Evaluation_date` DATE NOT NULL,
    `Evaluation_Grade` FLOAT NOT NULL,
    `Scientific_Field_Name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `fk_Project_Executive1_idx` (`Executive_ID` ASC),
    INDEX `fk_Project_Program1_idx` (`Program_ID` ASC),
    INDEX `fk_Project_Foundation1_idx` (`Foundation_ID` ASC),
    INDEX `fk_Project_Researcher2_idx` (`Researcher_ID_Boss` ASC),
    INDEX `fk_Project_Researcher3_idx` (`Researcher_ID_eval` ASC),
    INDEX `fk_Project_Scientific_Field1_idx` (`Scientific_Field_Name` ASC),
    CONSTRAINT `fk_Project_Executive1` FOREIGN KEY (`Executive_ID`)
        REFERENCES `mydb`.`Executive` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_Project_Program1` FOREIGN KEY (`Program_ID`)
        REFERENCES `mydb`.`Program` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_Project_Foundation1` FOREIGN KEY (`Foundation_ID`)
        REFERENCES `mydb`.`Foundation` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_Project_Researcher2` FOREIGN KEY (`Researcher_ID_Boss`)
        REFERENCES `mydb`.`Researcher` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_Project_Researcher3` FOREIGN KEY (`Researcher_ID_eval`)
        REFERENCES `mydb`.`Researcher` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_Project_Scientific_Field1` FOREIGN KEY (`Scientific_Field_Name`)
        REFERENCES `mydb`.`Scientific_Field` (`Name`)
        ON DELETE NO ACTION ON UPDATE CASCADE
)  ENGINE=INNODB;

-- -----------------------------------------------------
-- Table `Deliverable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Deliverable`;
CREATE TABLE IF NOT EXISTS `Deliverable` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `Title` VARCHAR(45) NOT NULL,
    `Summary` TEXT NULL,
    `Submission_Date` DATE NOT NULL,
    `Project_ID` INT NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `fk_Deliverable_Project1_idx` (`Project_ID` ASC),
    CONSTRAINT `fk_Deliverable_Project1` FOREIGN KEY (`Project_ID`)
        REFERENCES `Project` (`ID`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company`;
CREATE TABLE IF NOT EXISTS `Company` (
    `Equaty_Capitals` VARCHAR(45) NOT NULL,
    `Foundation_ID` INT NOT NULL,
    PRIMARY KEY (`Foundation_ID`),
    CONSTRAINT `fk_Company_Foundation1` FOREIGN KEY (`Foundation_ID`)
        REFERENCES `Foundation` (`ID`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `University`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `University`;
CREATE TABLE IF NOT EXISTS `University` (
    `Min_Edu_Budget` VARCHAR(45) NOT NULL,
    `Foundation_ID` INT NOT NULL,
    PRIMARY KEY (`Foundation_ID`),
    CONSTRAINT `fk_University_Foundation1` FOREIGN KEY (`Foundation_ID`)
        REFERENCES `Foundation` (`ID`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `Research_Center`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Research_Center`;
CREATE TABLE IF NOT EXISTS `Research_Center` (
    `Min_Edu_Budget` VARCHAR(45) NOT NULL,
    `Private_Budget` VARCHAR(45) NOT NULL,
    `Foundation_ID` INT NOT NULL,
    PRIMARY KEY (`Foundation_ID`),
    CONSTRAINT `fk_Research_Center_Foundation1` FOREIGN KEY (`Foundation_ID`)
        REFERENCES `Foundation` (`ID`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
